{{- if and .Values.azure.enabled .Values.azure.accountName .Values.azure.accountKey }}
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-azure-credentials
  labels:
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  azure.client.default.account: "{{ .Values.azure.accountName }}"
  azure.client.default.key: "{{ .Values.azure.accountKey }}"
{{- end }} 