{{- if .Values.snapshotAutomation.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "common.names.fullname" . }}-snapshot-job
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
spec:
  schedule: "{{ .Values.snapshotAutomation.schedule.cron | default "*/2 * * * *" }}"  # Every 2 minutes
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: snapshot-manager
            image: alpine:latest
            command: ["/bin/sh"]
            args:
            - -c
            - |
              # Install required packages
              apk add --no-cache curl jq && \
              set -euo pipefail
              
              # Configuration
              ELASTICSEARCH_URL="http://{{ include "common.names.fullname" . }}:{{ .Values.containerPorts.restAPI }}"
              REPOSITORY_NAME="azure-repo"
              SNAPSHOT_PREFIX="daily-snapshot"
              
              # Colors for output
              GREEN='\033[0;32m'
              RED='\033[0;31m'
              NC='\033[0m'
              
              log() {
                  echo -e "${GREEN}[$(date +'%Y-%m-%d %H:%M:%S')] $1${NC}"
              }
              
              error() {
                  echo -e "${RED}[$(date +'%Y-%m-%d %H:%M:%S')] ERROR: $1${NC}"
                  exit 1
              }
              
              # Wait for Elasticsearch to be ready
              wait_for_elasticsearch() {
                  log "Waiting for Elasticsearch to be ready..."
                  local max_attempts=30
                  local attempt=1
                  
                  while [ $attempt -le $max_attempts ]; do
                      if curl -s -f "$ELASTICSEARCH_URL/_cluster/health" > /dev/null 2>&1; then
                          log "Elasticsearch is ready!"
                          return 0
                      fi
                      
                      log "Attempt $attempt/$max_attempts: Elasticsearch not ready yet, waiting 10 seconds..."
                      sleep 10
                      attempt=$((attempt + 1))
                  done
                  
                  error "Elasticsearch failed to become ready after $max_attempts attempts"
              }
              
              # Create snapshot (exactly like manual command)
              create_snapshot() {
                  local snapshot_name="${SNAPSHOT_PREFIX}-$(date +%Y%m%d-%H%M%S)"
                  log "Creating snapshot '$snapshot_name'..."
                  
                  # Exact same configuration as manual command
                  local snapshot_config='{
                      "indices": "",
                      "ignore_unavailable": true,
                      "include_global_state": false
                  }'
                  
                  local response=$(curl -s -w "\n%{http_code}" -XPUT "$ELASTICSEARCH_URL/_snapshot/$REPOSITORY_NAME/$snapshot_name?wait_for_completion=true" \
                      -H 'Content-Type: application/json' \
                      -d "$snapshot_config")
                  
                  local http_code=$(echo "$response" | tail -n1)
                  local response_body=$(echo "$response" | head -n -1)
                  
                  if [ "$http_code" = "200" ]; then
                      log "Snapshot '$snapshot_name' created successfully"
                  else
                      error "Failed to create snapshot '$snapshot_name'. HTTP Code: $http_code, Response: $response_body"
                  fi
              }
              
              # Main execution
              main() {
                  log "Starting snapshot automation..."
                  
                  wait_for_elasticsearch
                  create_snapshot
                  
                  log "Snapshot automation completed successfully"
              }
              
              # Run main function
              main "$@"
            env:
            - name: azure.client.default.account
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.extraEnvVarsSecret | default "elasticsearch-azure-credentials" }}
                  key: azure.client.default.account
            - name: azure.client.default.key
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.extraEnvVarsSecret | default "elasticsearch-azure-credentials" }}
                  key: azure.client.default.key
            resources:
              requests:
                memory: "128Mi"
                cpu: "100m"
              limits:
                memory: "256Mi"
                cpu: "200m"
{{- end }} 