apiVersion: batch/v1
kind: CronJob
metadata:
  name: elasticsearch-snapshot
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: snapshot
              image: curlimages/curl:7.88.1
              env:
                - name: ELASTIC_PASSWORD
                  value: "changeme" # Replace with your actual password or use a secret
              command:
                - /bin/sh
                - -c
                - |
                  curl -X PUT -u elastic:${ELASTIC_PASSWORD} -H 'Content-Type: application/json' \
                    -d '{"indices": "*", "ignore_unavailable": true, "include_global_state": false}' \
                    http://elasticsearch-master:9200/_snapshot/azure_backup/snapshot-$(date +%Y-%m-%d-%H%M%S)?wait_for_completion=true
          restartPolicy: OnFailure 